version: '3'

services:
  app:
    container_name: winwin-api
    image: winwin-api
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - app
    working_dir: /app
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    command: [sh, -c, 'yarn start:dev']

  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 029285353
      POSTGRES_DB: winwin
    restart: on-failure
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: on-failure
    networks:
      - app
    volumes:
      - redis-data:/data

networks:
  app:

volumes:
  postgres-data:
  redis-data:
