version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - '8080:8080'
    networks:
      - winwin-backend-network
    restart: on-failure
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    networks:
      - winwin-backend-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    networks:
      - winwin-backend-network
    volumes:
      - redis-data:/data

networks:
  winwin-backend-network:

volumes:
  postgres-data:
  redis-data:
