version: '3'

services:
  app:
    container_name: winwin-api
    image: ghcr.io/cp23pl1/winwin-backend:latest
    ports:
      - '${PORT}:${PORT}'
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - app
    volumes:
      - ./service-account.json:/usr/src/app/service-account.json

  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: always
    expose:
      - '6379'
    networks:
      - app
    volumes:
      - redis-data:/data

networks:
  app:
    name: app

volumes:
  postgres-data:
  redis-data:
