version: '3'

services:
  app:
    container_name: winwin-api
    image: winwin-api
    build:
      context: .
    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      - postgres
      - redis
    networks:
      - app

  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: always
    networks:
      - app
    volumes:
      - redis-data:/data

networks:
  app:

volumes:
  postgres-data:
  redis-data:
