version: '3'

services:
  app:
    container_name: winwin-api
    image: winwin-api
    build:
      context: ./app
      target: development
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    networks:
      - app
    working_dir: /app
    volumes:
      - ./app:/app:delegated
      - ./app/node_modules:/app/node_modules
    command: yarn start:dev

  postgres:
    image: postgis/postgis:16-3.4-alpine
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: on-failure
    networks:
      - app
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    restart: on-failure
    env_file:
      - .env
    networks:
      - app
    volumes:
      - redis-data:/data

networks:
  app:

volumes:
  postgres-data:
  redis-data:
