name: Deploy on Self-hosted

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    runs-on: sit-virtual-machine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull image
        run: docker pull ghcr.io/${{ github.repository }}:latest
