name: Deploy on Self-hosted

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    runs-on: sit-virtual-machine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Login to Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and Run image
        run: |
          docker pull ghcr.io/${{ github.repository }}:main
          docker run --network=winwin-backend_app -d ghcr.io/${{ github.repository }}:main
