name: Deploy on Self-hosted

on:
  workflow_run:
    workflows: ['Build and Publish Docker Image']
    branches: ['main']
    types:
      - completed

env:
  CONTAINER_NAME: winwin-api
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: sit-virtual-machine
    steps:
      - name: Login to Container registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Stop container
        run: |
          docker stop ${{env.CONTAINER_NAME}} || true
          docker rm ${{env.CONTAINER_NAME}} || true

      - name: Remove image
        run: |
          docker rmi ${{steps.meta.outputs.tags}} || true

      - name: Setup Environment File
        run: |
          touch .env
          echo "NODE_ENV=production" >> .env
          echo "PORT=${{ vars.PORT }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env

      - name: Pull image and Run image from ${{ env.REGISTRY }}
        run: |
          docker pull ${{steps.meta.outputs.tags}}
          docker run -d \
            --name ${{env.CONTAINER_NAME}} \
            -p ${{vars.PORT}}:${{vars.PORT}} \
            --net winwin \
            --restart=always \
            --env-file .env \
          ${{steps.meta.outputs.tags}}
